<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UniqueBossFish</AssemblyName>
    <RootNamespace>EricSV.UniqueBossFish</RootNamespace>
    <Version>0.1.0</Version>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
